name: Publish Docker Image

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log into the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker image tags
        id: vars
        run: |
          TAG=${{ github.event.client_payload.tag }}
          echo "TAG_NAME=${TAG#refs/tags/}" >> $GITHUB_ENV
          echo "DOCKER_TAGS=coenraadhuman/directory-bot:latest,coenraadhuman/directory-bot:${TAG#refs/tags/}" >> $GITHUB_ENV
          echo "GHCR_TAGS=ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${TAG#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_TAGS }}
            ${{ env.GHCR_TAGS }}

      - name: Set Filebot Docker image tags
        id: vars
        run: |
          TAG=${{ github.event.client_payload.tag }}
          echo "TAG_NAME=${TAG#refs/tags/}" >> $GITHUB_ENV
          echo "FILEBOT_DOCKER_TAGS=coenraadhuman/directory-bot:filebot-latest,coenraadhuman/directory-bot:filebot-${TAG#refs/tags/}" >> $GITHUB_ENV
          echo "FILEBOT_GHCR_TAGS=ghcr.io/${{ github.repository }}:filebot-latest,ghcr.io/${{ github.repository }}:filebot-${TAG#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Filebot Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.FILEBOT_DOCKER_TAGS }}
            ${{ env.FILEBOT_GHCR_TAGS }}