name: Build and Create Draft Release

on:
  repository_dispatch:
    types: [trigger-release]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.tag }}

      - name: Generate New Release Ghangelog
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/coenraadhuman/gib:latest
          shell: /bin/bash
          options: -v ${{ github.workspace }}:/app
          run : |
            echo "=================="
            echo "Generate Changelog"
            echo "=================="
            gib changelog -p /app > RELEASE_CHANGELOG.md
            echo "Updated CHANGELOG.md"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: directory-bot-${{ github.event.client_payload.tag }}
          path: "./build/libs/directory-bot-*.jar"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: "./build/libs/directory-bot-*.jar"
          body_path: RELEASE_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFT }}
